Add bookings
RedStarMisha/java-shareit pull request #2
Opened 2022-09-05 11:44 UTC by RedStarMisha

2022-09-06 05:40 UTC, eugene-lenkevich requested changes
Привет, Михаил, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-09-06 05:40 UTC, eugene-lenkevich commented on pom.xml
> +			<version>2.6.6</version>
Вроде как можно не указывать версии стартеров, они должны подтягиваться из parent pom :)

![image](https://user-images.githubusercontent.com/94845100/188552207-2405a30f-2173-4183-b6c5-62203d9b3bb3.png)

2022-09-06 05:40 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public static Booking toEntity(User booker, Item item, BookingDtoEntry bookingDtoEntry) {
Пусть маппер будет спринговым бином, так же как сервисы. Статические методы лишний раз лучше не писать, это немножко против парадигмы спринга :)

2022-09-06 05:40 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        return booking != null ? new BookingShort(booking.getId(), booking.getBooker().getId()) : null;
Две подсказки, может пригодится :)

1.
return Optional.ofNullable(booking).ifPresent ((booking) ->  new BookingShort(...) ).orElse(null);

2. На BookingShort вешаем аннотацию ломбока @Builder, тогда можно будет писать вот так
var bookingShort = BookingShort.builder()
.id(booking.getId)
....
.build()

2022-09-06 05:40 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        } else if (state.equals("CURRENT")) {
А не лучше ли тут использовать enum, а не сравнивать строки? :)

2022-09-06 05:40 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForResponse.java
> +public interface BookingForResponse {
А не переусложнение ли тут, столько разных dto :)

Далее, а верно ли семантически название ForResponse, на уровне сервиса мы абстрагируемся от того как будут дальше использоваться данные, а тут мы указываем на дальнейшее предназначение (ответ в web-слое если я правильно понимаю). Скорее на подумать, глобально не надо ничего менять :)

2022-09-07 06:08 UTC, RedStarMisha commented on pom.xml
> +			<version>2.6.6</version>
Если я правильно понял, то у родителя в его pom.xml должна быть указана версия. А ее там нет. Если удалить строку version отсюда перестает работать )
https://cwiki.apache.org/confluence/display/MAVENOLD/Automatic+Parent+Versioning

2022-09-07 06:19 UTC, eugene-lenkevich commented on pom.xml
> +			<version>2.6.6</version>
Нет версии spring-boot-starter-data-jpa то? :)
Не совсем понял, убрал версию, собрал через clean package, у меня собралось все, или ты про что-то другое?
![image](https://user-images.githubusercontent.com/94845100/188803122-0e94cd78-631d-4b6d-9e64-aad261035785.png)

2022-09-07 09:33 UTC, eugene-lenkevich approved these changes
Привет, вижу удалось разобраться с типами даты и времени :)
Все гут, спасибо!

2022-09-22 10:36 UTC, merged